### ISSUE TITLE
UI fork API call not working

### ISSUE THREAD

**Issue by developer-devo** [raydium-io/raydium-ui-v3#5]
Hi there, we are forking the UI but the api calls are not working

https://transaction-v1.raydium.io/compute/swap-base-in?inputMint=So11111111111111111111111111111111111111112&outputMint=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&amount=1000000&slippageBps=50&txVersion=V0

is the API call.

**Comment by cruzshia** [comment]
swap doesn't open to public at this moment, if we do, will announcement in the future
